[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.11.0
    mikalhart/TinyGPSPlus @ ^1.0.3
    mathieucarbou/ESPAsyncWebServer @ ^3.3.22
    bblanchon/ArduinoJson @ ^6.21.3
    mcauser/i2cdetect @ ^1.0.0